const express = require('express')

const router = express.Router()

const auth = require('./routes/auth')
const admin = require('./routes/admin')
const product = require('./routes/product')
const template = require('./routes/template')
const category = require('./routes/category')
const badge = require('./routes/badge')
const faq = require('./routes/faq')
const ingredient = require('./routes/ingredient')
const banner = require('./routes/banner')
const staticPage = require('./routes/staticPage')
const configuration = require('./routes/configuration')
const discount = require('./routes/discount')
const coupon = require('./routes/coupon')
const blog = require('./routes/blog')
const dummy = require('./routes/dummy')
const verifyAdminAccessToken = require('../../middleware/verifyAdminAccessToken')

router.use('/auth', auth)
router.use('/admin', verifyAdminAccessToken, admin)
router.use('/product', verifyAdminAccessToken, product)
router.use('/template', verifyAdminAccessToken, template)
router.use('/category', category)
// router.use('/category', verifyAdminAccessToken, category)
router.use('/badge', verifyAdminAccessToken, badge)
router.use('/faq', verifyAdminAccessToken, faq)
router.use('/ingredient', verifyAdminAccessToken, ingredient)
router.use('/discount', verifyAdminAccessToken, discount)
router.use('/coupon', verifyAdminAccessToken, coupon)
router.use('/banner', verifyAdminAccessToken, banner)
router.use('/staticPage', verifyAdminAccessToken, staticPage)
router.use('/configuration', verifyAdminAccessToken, configuration)
router.use('/blog', verifyAdminAccessToken, blog)
router.use('/dummy', dummy)

module.exports = router
